### ISSUE TITLE
KeyError: 'count'

### ISSUE THREAD

**Issue by ZuluSpl0it** [MultiChain/multichain-explorer-2#5]
First, let me say that multichain is awesome. I just started using explorer-2 today and noticed an issue.

When I click on the Asset number in the summary (http://147.182.214.238:4444/base_chain/assets), I get this error on the console:

base_chain: ----------------------------------------
Exception occurred during processing of request from ('68.206.160.142', 1600)
Traceback (most recent call last):
  File "/usr/lib/python3.10/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.10/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/lib/python3.10/http/server.py", line 432, in handle
    self.handle_one_request()
  File "/usr/lib/python3.10/http/server.py", line 420, in handle_one_request
    method()
  File "/root/.multichain/base_chain/multichain-explorer-2/server.py", line 94, in do_GET
    content=self.handler(self.chain,self.params,self.nparams)
  File "/root/.multichain/base_chain/multichain-explorer-2/data.py", line 1168, in handle_assets
    response=chain.request("listassets",['*', False,  nparams['count'], nparams['start']])
KeyError: 'count'
----------------------------------------

The webpage stays stuck on loading.

**Comment by gidgreen** [comment]
Thanks for the report, I'll pass this on to the dev team and get back to you.

**Comment by gidgreen** [comment]
This bug should now be fixed, please pull the latest version. And thanks again for reporting it.

**Comment by ZuluSpl0it** [comment]
Awesome - I confirmed that it works now. Closing as resolved.
